properties = [
  {
    name: "barre",
    product_id: product.id,

    ref: "K6103",
    description: "Porteur",
    packing: 7000,
    price_cents: 65_45,
  },
  {
    name: "Joint porteur",
    ref: "U612",
    description: "Joint porteur",
    packing: 12000,
    product_id: product.id,
    price_cents: 33_79,
  },
  {
    name: "Serreur",
    ref: "K6201",
    description: "Serreur",
    packing: 6000,
    product_id: product.id,
    price_cents: 14_06,
  },
  {
    name: "Joint serreur",
    ref: "U622",
    description: "Joint serreur",
    packing: 250000,
    product_id: product.id,
    price_cents: 12_38,
  },
  {
    name: "Capots",
    ref: "K6212",
    description: "Capots",
    packing: 7000,
    product_id: product.id,
    price_cents: 15_63,
  },
  {
    name: "Joint rupture mousse",
    ref: "H241",
    description: "Joint mousse",
    packing: 6000,
    product_id: product.id,
    price_cents: 7_14,
  },
  {
    name: "Profil obturation",
    ref: "T610",
    description: "Profil lat 1",
    packing: 3500,
    product_id: product.id,
    price_cents: 6_70,
  },
  {
    name: "Profil obturation",
    ref: "T612",
    description: "Profil lat 2",
    packing: 3500,
    product_id: product.id,
    price_cents: 4_06,
  },
  {
    name: "Tole a commande",
    ref: "",
    description: "Toles",
    packing: 1000,
    product_id: product.id,
    price_cents: 14_00,
  },
  {
    name: "Connecteurs",
    ref: "",
    description: "",
    product_id: product.id,
    price_cents: 2_09,
  },
  {
    name: "Vis",
    ref: "CBP1100",
    description: "",
    packing: 100,
    product_id: product.id,
    price_cents: 25_00,
  },
  {
    name: "Vitrage",
    ref: "",
    description: "",
    product_id: product.id,
    price_cents: 60_63,
  },
  {
    name: "Compribande",
    ref: "",
    description: "",
    product_id: product.id,
    price_cents: 22_50,
  },
]